version: '3.7'

services:
#  mssql:
#    container_name: mssql-for-tests
#    image: "mcr.microsoft.com/mssql/server:2017-latest"
#    ports:
#      - "14333:1433"
#    environment:
#      SA_PASSWORD: MySecretePass3323
#      ACCEPT_EULA: Y
#    volumes:
#      - ./src/main/resources/db/init-db.sql:/scripts

  postgres:
    container_name: awnext-postgres-tests
    image: postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: awnext
      POSTGRES_USER: awnext
      POSTGRES_PASSWORD: 12345
